name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_build.txt
    - name: Lint with black
      run: |
        black --preview --config pyproject.toml --check ./
    - name: Flake8
      run: |
        flake8 --exclude=.git,*migrations*,venv,docs
    - name: Docstrings
      run: |
        pydocstyle --convention=numpy --add-ignore=D412 binsmooth.py
    - name: Tests
      run: |
        pytest
